export 'package:widgets_app/Presentation/screens/animated/animated_screen.dart';
export 'package:widgets_app/Presentation/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widgets_app/Presentation/screens/buttons/buttons_screen.dart';
export 'package:widgets_app/Presentation/screens/cards/card_screen.dart';
export 'package:widgets_app/Presentation/screens/home/home_screen.dart';
export 'package:widgets_app/Presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgets_app/Presentation/screens/progress/progress_screen.dart';
export 'package:widgets_app/Presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widgets_app/Presentation/screens/ui_control/ui_control_screen.dart';